routes/web.php
    Route::get('/index/void-usage/', 'ReportCollectionController@index_collection_void_usage')->name('index.collection.void-usage');
    Route::get('/voidUsageCollection', 'ReportCollectionController@voidUsageCollectionOutlet')->name('void-usage.collection');
    // END

    //report
    Route::get('/collection/outlet/', 'ReportCollectionController@index_collection_outlet')->name('index.collection.outlet');
    Route::get('/collection/outlet/print-pdf', 'ReportCollectionController@all_collection_outlet')->name('all.collection.outlet');
    Route::get('/detailCollection', 'ReportCollectionController@detailCollectionOutlet')->name('detail.collection');
    Route::get('/subtotalCollection', 'ReportCollectionController@subtotalCollectionOutlet')->name('subtotal.collection');
    Route::get('/grandtotalCollection', 'ReportCollectionController@grandtotalCollectionOutlet')->name('grandtotal.collection');
    Route::get('/totalCollection', 'ReportCollectionController@totalCollectionOutlet')->name('total.collection');
    Route::get('/cashierCollection', 'ReportCollectionController@cashierCollectionOutlet')->name('cashier.collection');
    //Route::get('/totDataCollection', 'ReportCollectionController@totCollectionOutlet')->name('tot.collection');
    //Route::get('/balanceDataCollection', 'ReportCollectionController@balanceCollectionOutlet')->name('balance.collection');

    Route::get('/index/collection/activity/', 'ReportCollectionController@index_collection_activity')->name('index.collection.activity');
    Route::get('/report/collection/activity', 'ReportCollectionController@collection_activity')->name('report.collection.activity');
    Route::post('/choose/activity', 'ReportCollectionController@choose_activity')->name('choose.activity');

    Route::get('/index/collection/payment/', 'ReportCollectionController@index_collection_payment')->name('index.collection.payment');
    Route::get('/payment_type_collection', 'ReportCollectionController@payment_type_collection')->name('payment_type.collection.payment');
    Route::get('/bank_payment_collection', 'ReportCollectionController@bank_payment_collection')->name('bank.collection.payment');
    Route::get('/detail_payment_collection', 'ReportCollectionController@detail_payment_collection')->name('detail.collection.payment');

    Route::get('/index/collection/redeem-point/', 'ReportCollectionController@index_collection_redeem_point')->name('index.collection.redeemPoint');
    Route::get('/summary/collection/redeem-point/', 'ReportCollectionController@summary_collection_redeem_point')->name('summary.collection.redeemPoint');
    Route::get('/detail/collection/redeem-point/', 'ReportCollectionController@detail_collection_redeem_point')->name('detail.collection.redeemPoint');


    Route::get('/index/item/sold/collection', 'ReportItemController@index_item_sold_collection')->name('index.item.sold.collection');
    Route::match(array('GET', 'POST'), '/report/item/sold/collection', 'ReportItemController@item_sold_collection')->name('report.item.sold.collection');

    Route::get('/index/item/sold/', 'ReportItemController@index_item_sold_outlet')->name('index.item.sold.outlet');
    Route::match(array('GET', 'POST'), '/report/item/sold', 'ReportItemController@item_sold_outlet')->name('report.item.sold.outlet');

    Route::get('/index/treatment-done/outlet/', 'ReportDoneController@index_treatmentdone_outlet')->name('index.treatment-done.outlet');
    Route::get('/report/treatment-done/outlet/summary', 'ReportDoneController@treatmentdone_outlet_summary')->name('treatment-done.outlet.summary');
    Route::get('/report/treatment-done/outlet/detail', 'ReportDoneController@treatmentdone_outlet_detail')->name('treatment-done.outlet.detail');
    Route::get('/report/treatment-done/outlet2/material', 'ReportDoneController@treatmentdone_outlet_material')->name('treatment-done.outlet.details.material');

    Route::get('/index/product-done/outlet/', 'ReportDoneController@index_productdone_outlet')->name('index.product-done.outlet');
    Route::get('/report/product-done/outlet/detail', 'ReportDoneController@productdone_outlet_detail')->name('product-done.outlet.detail');

    Route::get('/index/treatment-done/therapist/', 'ReportDoneController@index_treatmentdone_therapist')->name('index.treatment-done.therapist');
    Route::get('/report/treatment-done/therapist', 'ReportDoneController@treatmentdone_therapist')->name('treatment-done.therapist');
    Route::get('/report/treatment-done/Satisfaction', 'ReportDoneController@summaryCustomerSatisfaction')->name('treatment-done.satisfaction');

    Route::get('/index/revenue/', 'ReportRevenueController@index_revenue')->name('index.revenue');
    Route::get('/report/revenue', 'ReportRevenueController@revenue')->name('report.revenue');

    Route::get('/index/commission/sales', 'ReportCommission@indexCommissionSales')->name('index.commission.sales');
    Route::get('/report/commission/sales/summary', 'ReportCommission@summarySales')->name('report.summary.sales');
    Route::get('/report/commission/sales', 'ReportCommission@commissionSales')->name('report.commission.sales');

    Route::get('/index/commission/consultant', 'ReportCommission@indexCommissionConsultant')->name('index.commission.consultant');
    Route::get('/report/commission/consultant/summary', 'ReportCommission@summaryConsultant')->name('report.summary.consultant');
    Route::get('/report/commission/consultant', 'ReportCommission@commissionConsultant')->name('report.commission.consultant');

    Route::get('/index/commission/therapist', 'ReportCommission@indexCommissionTherapist')->name('index.commission.therapist');
    Route::get('/report/commission/therapist/summary', 'ReportCommission@summaryTherapist')->name('report.summary.therapist');
    Route::get('/report/commission/therapist', 'ReportCommission@commissionTherapist')->name('report.commission.therapist');

    Route::get('/index/commission/therapist-doing', 'ReportCommission@indexCommissionTherapistDoing')->name('index.commission.therapist-doing');
    Route::get('/report/commission/therapist-doing/summary', 'ReportCommission@summaryTherapistDoing')->name('report.summary.therapist-doing');
    Route::get('/report/commission/therapist-doing', 'ReportCommission@commissionTherapistDoing')->name('report.commission.therapist-doing');

    Route::get('/agent/list', 'AgentController@list')->name('agent.list');
    Route::get('/agent/listData', 'AgentController@listData')->name('agent.listData');
    Route::get('/agent/rejectData', 'AgentController@rejectData')->name('agent.rejectData');
    Route::get('/agent/active', 'AgentController@active')->name('agent.active');
    Route::get('/agent/activeData', 'AgentController@activeData')->name('agent.activeData');
    Route::patch('/agent/{id}/takeout', 'AgentController@takeOut')->name('agent.takeOut');
    Route::get('/agent/{id}/detail', 'AgentController@detailAgent');
    Route::patch('/agent/{id}/enable', 'AgentController@enableAgent')->name('agent.enableAgent');
    Route::get('/agent/client', 'AgentController@alreadyClient');
    Route::post('/agent/client/store', 'AgentController@storeClient')->name('agent.client.store');
    Route::resource('/agent', 'AgentController');

    Route::group(['prefix' => 'dr-review', 'as' => 'dr-review.'], function () {
        Route::get('', 'DoctorReviewController@index')->name('index');
        Route::get('upload', 'DoctorReviewController@upload')->name('upload');
        Route::post('upload', 'DoctorReviewController@uploadStore')->name('upload.store');

        Route::get('history', 'DoctorReviewController@history')->name('history');
        Route::get('history/{id}', 'DoctorReviewController@historyDetail')->name('history.detail');
        Route::delete('history/{id}', 'DoctorReviewController@historyDestroy')->name('history.destroy');

        Route::get('photo/{id}', 'DoctorReviewController@photo')->name('photo');

        Route::get('sandingkan', 'DoctorReviewController@sandingkan')->name('sandingkan');
        Route::post('sandingkan', 'DoctorReviewController@sandingkanCustomer')->name('sandingkan.customer');


        Route::post('get-photo', 'DoctorReviewController@getPhoto')->name('sandingkan.photo');
        Route::post('get-treatment', 'DoctorReviewController@getTreatment')->name('sandingkan.treatment');
    });

    Route::get('/anamnesas', 'AnamnesaController@render');

    Route::resource('survey', 'SurveyController');
    Route::get('/faq', 'FaqController@index')->name('faq');

    Route::get('/izzibook/patients', 'IzzibookSyncController@patients')->name('izzibook.patients');
    Route::get('/izzibook/patients/data', 'IzzibookSyncController@patientsData')->name('izzibook.patients.data');
    Route::get('/izzibook/invoices', 'IzzibookSyncController@invoices')->name('izzibook.invoices');
    Route::get('/izzibook/invoices/data', 'IzzibookSyncController@invoicesData')->name('izzibook.invoices.data');
    Route::get('/izzibook/payments', 'IzzibookSyncController@payments')->name('izzibook.payments');
    Route::get('/izzibook/payments/data', 'IzzibookSyncController@paymentsData')->name('izzibook.payments.data');
    Route::get('/izzibook/orders', 'IzzibookSyncController@purchaseOrders')->name('izzibook.orders');
    Route::get('/izzibook/warehouse_mutations', 'IzzibookSyncController@warehouseMutations')->name('izzibook.warehouse_mutations');
    Route::get('/izzibook/finished_products', 'IzzibookSyncController@finishedProduct')->name('izzibook.finished_products');
    Route::get('/izzibook/patients/{code}', 'IzzibookSyncController@retryPatient');
    Route::get('/izzibook/invoices/{code}', 'IzzibookSyncController@retryInvoice');
    Route::get('/izzibook/payments/{code}', 'IzzibookSyncController@retryPayment');
    Route::get('/izzibook/orders/{code}', 'IzzibookSyncController@retryPurchaseOrder');
    Route::get('/izzibook/finished_proudcts/{code}', 'IzzibookSyncController@retryFinishedProduct');
});

app/Models/Agent.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    protected $table = 'agents';
    protected $primaryKey = 'id_agent';

    public static function generateAgentCode()
    {
        $now = Carbon::now();
        $array = Agent::whereMonth('created_at', $now->month)
        ->whereYear('created_at', $now->year)
        ->get()
        ->toArray();

        if ($array == []) {
            $number = 001;
            $idinvcode =
                "EA-".$now->isoFormat('YYYY').
                $now->isoFormat('MM').
                sprintf('%03d', $number);
        } else {
            $number = substr(end($array)['agent_code'], -4)+1;
            $idinvcode =
                "EA-".$now->isoFormat('YYYY').
                $now->isoFormat('MM').
                sprintf('%03d', $number);
        }
        return $idinvcode;
    }

    public function customer()
    {
        return $this->belongsTo('App\Models\Customer', 'agent_code', 'induk_customer');
    }
}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Gate;

use App\Models\Agent;
use App\Models\Invoice;

class AgentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            if (Gate::allows('admin')) {
                return $next($request);
            }
            abort(403, 'You do not have enough access rights');
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('agent.index');
    }

    public function list()
    {
        return view('agent.list');
    }

    public function listData()
    {
        $agent = Agent::where('status', 0)->whereNull('uniq_code')->get();
        $data = array();
        $no = 1;
        foreach ($agent as $list) {
            $row = [];
            $row[] = $no++;
            $row[] = $list->created_at->format('d/m/Y');
            $row[] = $list->agent_name;
            $row[] = $list->phone;
            $row[] = $list->email;
            $row[] = $list->address;
            $row[] = '<div class="btn-group">
                        <a class="btn btn-success btn-xs"  onclick="approve(\'' . $list->id_agent . '\')">
                            <i class="fa fa-check"></i>
                        </a>
                        <a class="btn btn-danger btn-xs"  onclick="deleteData(\'' . $list->id_agent . '\')">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>';

            $data[] = $row;
        }
        return DataTables::of($data)->escapeColumns([])->make(true);
    }

    public function rejectData()
    {
        $agent = Agent::where('status', 1)->get();
        $data = array();
        $no = 1;
        foreach ($agent as $list) {
            $row = [];
            $row[] = $no++;
            $row[] = $list->created_at->format('d/m/Y');
            $row[] = $list->agent_name;
            $row[] = $list->phone;
            $row[] = $list->email;
            $row[] = $list->address;
            $row[] = '<div class="btn-group">
                        <a class="btn btn-success btn-xs"  onclick="enableAgent(\'' . $list->id_agent . '\')">
                            <i class="fa fa-check"></i>
                        </a>
                    </div>';
            $data[] = $row;
        }
        return DataTables::of($data)->escapeColumns([])->make(true);
    }

    public function active()
    {
        return view('agent.active');
    }

    public function activeData()
    {
        $agent = Agent::where('status', 0)->whereNotNull('uniq_code')->get();
        $data = array();
        $no = 1;
        foreach ($agent as $list) {
            $row = [];
            $row[] = $no++;
            $row[] = $list->created_at->format('d/m/Y');
            $row[] = $list->agent_name;
            $row[] = $list->phone;
            $row[] = $list->email;
            $row[] = $list->address;
            $row[] = '<div class="btn-group">
                        <a class="btn btn-info btn-xs"  onclick="detail(\'' . $list->id_agent . '\')">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-warning btn-xs"  onclick="takeOut(\'' . $list->id_agent . '\')">
                            Take Out
                        </a>
                    </div>';
            $data[] = $row;
        }
        return DataTables::of($data)->escapeColumns([])->make(true);
    }

    public function store(Request $request)
    {
        $request->validate([
            'email' => 'unique:agents|max:255',
            'phone' => 'unique:agents|numeric',
        ]);

        $agent = new Agent;
        $agent->agent_name = $request->name;
        $agent->email = $request->email;
        $agent->agent_code = Agent::generateAgentCode();
        $agent->phone = $request->phone;
        $agent->address = $request->address;
        $agent->save();
    }

    public function detailAgent($id)
    {
        $invoice = Invoice::where('void_invoice', 0)
            ->where('agent_id', $id)->get()->groupBy('customer_id');

        $data = array();
        $payments = 0;
        foreach ($invoice as $list) {
            foreach ($list as $key) {
                foreach ($key->payment as $payment) {
                    $payments += str_replace(array('.', ','), "", $payment->amount);
                }
            }
            $row = [];
            $row[] = $list[0]->customer->induk_customer;
            $row[] = $list[0]->customer->full_name;
            $row[] = $list[0]->customer->phone;
            $row[] = $list[0]->customer->ktp;
            $row[] = $list[0]->customer->email;
            $row[] = format_money($payments);
            $data[] = $row;
        }
        return DataTables::of($data)->escapeColumns([])->make(true);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Agent::find($id);
        $update->username = Str::before($update->email, '@');
        $update->password = Hash::make('123456789');
        $update->active_date = now();
        $update->uniq_code = str_random(30);
        $update->update();
    }

    public function takeOut($id)
    {
        $update = Agent::find($id);
        $update->status = 1;
        $update->update();
    }

    public function enableAgent($id)
    {
        $update = Agent::find($id);
        $update->status = 0;
        $update->update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Agent::find($id)->delete();
    }

    public function alreadyClient()
    {
        return view('agent.already');
    }

    public function storeClient(Request $request)
    {
        $request->validate([
            'email' => 'unique:agents|max:255',
            'phone' => 'unique:agents|numeric',
        ]);

        $agent = new Agent;
        $agent->agent_name = $request->name;
        $agent->email = $request->email;
        $agent->agent_code = $request->agent_code;
        $agent->phone = $request->phone;
        $agent->address = $request->address;
        $agent->save();
    }
}

resources/views/agent/active.blade.php
@extends('base')

@section('title')
Agent List
@endsection

@section('breadcrumb')
@parent
<li>Agent List</li>
@endsection

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box box-solid">
            <div class="box-header with-border">
                <span style="font-size:20px;">Active Agent</span>
                <p style="font-size:15px;"><i>List sales agent dengan status aktif.</i></p>
            </div>
            <div class="box-body">
                <table class="activeoke table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                    <thead>
                        <tr>
                            <th width="10%">No</th>
                            <th>Reg Date</th>
                            <th>Agent Name</th>
                            <th>Contact</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th class="all" width="10%">Action</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@include('agent.detail')
@endsection

@section('script')
<script type="text/javascript">
    var table, table_active, table_detail, save_method;

$(function () {
    table = $('.activeoke').DataTable({
        "processing": true,
        "serverside": true,
        "ajax": {
            "url": "{{ route('agent.activeData') }}",
            "type": "GET"
        }
    });
});

function takeOut(id) {
    swal({
        title: "Are you Sure?",
        text: "Agent Will be Disabled",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
            $.ajax({
                url : "/agent/"+id+"/takeout",
                type : "POST",
                data : {'_method' : 'patch', '_token' : $('meta[name=csrf-token]').attr('content')},
                success : function(data){
                    swal({
                        icon: "success"
                    })
                    table.ajax.reload();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    swal("Error deleting!", "Please try again", "error");
                }
            });
        }
    });
}

function detail(id) {
    
    $.ajax({
        url : "/agent/"+id+"/detail",
        type: 'GET',
        contentType: "application/json",                
        success: function(data) {
            $('#modal-form').modal('show');
            $(".detail-oke").dataTable().fnDestroy()                   
            table_detail = $('.detail-oke').DataTable({
                    "ordering" : false
            });
            
            table_detail.clear();
            table_detail.rows.add(data.data);
            table_detail.draw();     
        },
        error: function () {
            alert('error');
        }
    });

}
</script>
@endsection

resources/views/agent/detail.blade.php
<div class="modal" id="modal-form" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fa fa-times fa-lg"></i>
                </button>
                <h3 class="modal-title">Detail Agent</h3>
            </div>
            <div class="modal-body">
                <div class="box-body">                
                    <table class="detail-oke table table-striped table-bordered nowrap table-collection">
                        <thead>
                            <tr>
                                <th>Reff Number</th>
                                <th>Full Name</th>
                                <th>Contact</th>
                                <th>KTP ID</th>
                                <th>Email</th>
                                <th>Numb Of Sales</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Reff Number</td>
                                <td>Full Name</td>
                                <td>Contact</td>
                                <td>KTP ID</td>
                                <td>Email</td>
                                <td>Numb Of Sales</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            {{-- <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Save </button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                        class="fa fa-arrow-circle-left"></i> Cancel</button>
            </div> --}}
        </div>
    </div>
</div>

resources/views/agent/index.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>POS Agent</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('font-awesome/css/font-awesome.min.css') }}">
  {{-- select --}}
  <link rel="stylesheet" href="{{ asset('plugins/select2/select2.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">

  <link rel="stylesheet" href="{{ asset('plugins/iCheck/square/blue.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('dist/css/skins/_all-skins.min.css') }}">

  <link href='{{ asset('css/fontGoogle.css') }}' rel='stylesheet' />

</head>

<body class="hold-transition register-page">
  <div class="register-box">
    <div class="register-logo">
      <a href="../../index2.html"><b>POS</b>Agent</a>
    </div>
    <a href="{{ url('/agent/client') }}">
      <button type="button" class="btn btn-danger btn-block btn-flat">
        CLICK HERE !!! for Already Client
      </button>
    </a>
    <div class="register-box-body">
      <p class="login-box-msg">Register a new Agent</p>

      <div class="alert alert-danger hidden">
        <ul>
          <li id="email" class="hidden"></li>
          <li id="phone" class="hidden"></li>
        </ul>
      </div>

      <form id="form-created" data-toggle="validator" method="post">
        {{ csrf_field() }} {{ method_field('POST') }}
        <div class="form-group has-feedback">
          <input type="text" class="form-control" name="name" placeholder="Full name" required>
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="email" name="email" id="emailx" class="form-control" placeholder="Email" required>
          <span class="glyphicon emailx glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone" required>
          <span class="glyphicon glyphicon-phone form-control-feedback"></span>
        </div>

        <div class="form-group has-feedback">
          <textarea name="address" id="address" class="form-control" cols="40" rows="5" placeholder="Address"
            required></textarea>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox" required> I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.form-box -->
  </div>
  <!-- /.register-box -->

  <!-- jQuery 3 -->
  <script src="{{ asset('plugins/jQuery/jquery.min.js') }}"></script>

  <script src="{{ asset('plugins/morris/morris.min.js') }}"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="{{ asset('plugins/jQueryUI/jquery-ui.min.js') }}"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button);
  </script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
  <!-- Sparkline -->
  <script src="{{ asset('plugins/sparkline/jquery.sparkline.min.js') }}"></script>
  <!-- jvectormap -->
  <script src="{{ asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
  <script src="{{ asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
  <!-- jQuery Knob Chart -->
  <script src="{{ asset('plugins/knob/jquery.knob.js') }}"></script>
  <script src="{{ asset('plugins/iCheck/icheck.min.js') }}"></script>
  <!-- daterangepicker -->
  <script src="{{ asset('plugins/daterangepicker/moment.min.js') }}"></script>
  <script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
  <!-- datepicker -->
  <script src="{{ asset('plugins/datepicker/bootstrap-datepicker.js') }}"></script>
  <!-- Slimscroll -->
  <script src="{{ asset('plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
  <!-- FastClick -->
  <script src="{{ asset('plugins/fastclick/fastclick.min.js') }}"></script>
  <!-- AdminLTE App -->
  <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->

  <script src="{{ asset('dist/js/demo.js') }}"></script>
  <script src="{{ asset('js/validator.js') }}"></script>
  <script src="{{ asset('plugins/sweetalert/sweetalert.min.js') }}"></script>

  <script>
    $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });

    //$('.alert').css('display', 'block').delay(10000).fadeOut();

    $('#form-created').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         $.ajax({
            url : "{{ route('agent.store') }}",
            type : "POST",
            data : $('#form-created').serialize(),
           success : function(data){
              swal({
                  title: "Successfully Create",
                  icon: "success",
                  buttons: "Oke",
              })
              .then((print) => {
                  swal("wait 1 x 24 hours, admin will process")
                  .then((oke) => {
                      window.location.href = "{{ route('agent.list') }}";
                  });
              });
           },
           error : function(e){
              if (e.responseJSON.errors) {
                if (e.responseJSON.errors.email) {
                  
                  $('#emailx').parents('.form-group').addClass('has-error').removeClass('has-success');
                  $('.emailx').removeClass('glyphicon-ok').addClass('glyphicon-remove');
                  $('#email').text(e.responseJSON.errors.email).removeClass('hidden');
                  }
                  $('.alert').removeClass('hidden');
                  $('.alert').css('display', 'block').delay(10000).fadeOut();
                  $('#phone').text(e.responseJSON.errors.phone).removeClass('hidden');
              }
             }
         });
         return false;
      }
    });
  });

  </script>
</body>

</html>