routes/web.php
    Route::patch('/appointment/by-room/{id}/status', 'AppointmentController@changeStatus');
    Route::resource('/appointment', 'AppointmentController');

    Route::match(array('GET', 'POST'), '/dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('/all-outlet/', 'DashboardController@all_outlet')->name('all.outlet');
    Route::get('/invoice/dashboard/{id}', 'DashboardController@InvoiceToday')->name('invoice.dashboard');
    Route::match(array('GET', 'POST'), '/dashboard/geografis', 'DashboardController@geografis')->name('dashboard.geografis');
    Route::match(array('GET', 'POST'), '/dashboard/productranking', 'DashboardController@productRanking')->name('dashboard.productranking');
    Route::match(array('GET', 'POST'), '/dashboard/treatmentranking', 'DashboardController@treatmentRanking')->name('dashboard.treatmentranking');
    Route::match(array('GET', 'POST'), '/dashboard/alldata', 'DashboardController@allData')->name('dashboard.alldata');

    //invoice-create
    Route::get('invoice-create/{id_invoice}/sign', 'InvoiceController@sign')->name('invoice.sign');
    Route::post('invoice-create/{id_invoice}/sign', 'InvoiceController@updateSign')->name('invoice.update-sign');
    Route::get('invoice-create/{id_invoice}/print', 'InvoiceController@generatePdf')->name('invoice.print');
    Route::get('invoice-create/{id_invoice}/print-thermal', 'InvoiceController@generateThermalPdf')->name('invoice.print-thermal');
    Route::get('invoice-create/{id_invoice}/wa', 'InvoiceController@sendWhatsApp')->name('invoice.wa');
    Route::get('/invoice-create/{id}/chooseAnamnesa', 'InvoiceController@getAnamnesa');
    Route::get('/invoice-create/{id}/loadAnamnesa', 'InvoiceController@loadAnamnesa');
    Route::get('/invoice-convert/{id}/data', 'InvoiceConvertController@listData')->name('invoice-convert.data');
    Route::get('/invoice-create/{id}/chooseWarehouse', 'InvoiceController@getWarehouse');
    Route::resource('/invoice-create', 'InvoiceController');

    //invoice-package
    Route::get('/packages/{id}/choosePackage', 'InvoiceController@getPackage');
    Route::get('/activity/{activity_id}/{item_type}/{item_id}/chooseActivity', 'InvoiceController@getActivity');

    //invoice-convert
    Route::get('invoice-convert/{id_invoice}/print', 'InvoiceConvertController@generatePdf')->name('invoice-convert.print');
    Route::resource('/invoice-convert', 'InvoiceConvertController');

    Route::get('/invoice-balance/{id}/print', 'InvoiceBalanceController@generatePdf')->name('invoice-balance.print');
    Route::patch('/invoice-balance/{id}/void', 'InvoiceBalanceController@void')->name('invoice-balance.void');
    Route::get('/invoice-balance/{id}/invoice', 'InvoiceBalanceController@getInvoice');
    Route::get('/invoice-balance/{id}/loadInvoice', 'InvoiceBalanceController@loadInvoice');
    Route::resource('/invoice-balance', 'InvoiceBalanceController');

    //invoice-point
    Route::get('invoice-point/{id_invoice}/print-thermal', 'InvoicePointController@generateThermalPdf')->name('invoice.point.print-thermal');
    Route::get('invoice-point/{id_invoice}/print', 'InvoicePointController@generatePdf')->name('invoice.point.print');

    Route::resource('/invoice-point', 'InvoicePointController');

    //product point
    Route::get('/productpoints/{id}/chooseProduct', 'ItemMaster\ProductPointController@chooseProduct');
    Route::get('/productpoints/data', 'ItemMaster\ProductPointController@listData')->name('productpoints.data');
    Route::resource('/productpoints', 'ItemMaster\ProductPointController');

    // Route::post('/package/keyword', 'InvoiceController@getDiscount')->name('discount.keyword');
    // Route::post('/package/all', 'InvoiceController@getAllDiscount')->name('discount.all');

    //getDPAppBalance
    Route::get('/customers/{id}/dpAppBalance', 'CustomerController@get_dp_balance');

    //customers
    Route::get('/customers/data', 'CustomerController@listData')->name('customers.data');
    Route::post('/customers/upload', 'CustomerController@upload')->name('customers.upload');
    Route::get('/customers/export', 'CustomerController@export')->name('customers.export');
    Route::get('/customers/export-excel', 'CustomerController@exportExcel')->name('customers.export-excel');
    Route::get('/customers/{id}/province', 'CustomerController@getProvince');
    Route::post('/customer/{id}/delete-outlet', 'CustomerController@destroyCustomerOutlet')->name('customers.outlet.destroy');
    Route::post('/customer/{id}/delete-consultant', 'CustomerController@destroyCustomerConsultant')->name('customers.consultant.destroy');
    Route::post('/customer/{id}/outlet', 'CustomerController@storeCustomerOutlet')->name('customers.outlet.store');
    Route::post('/customer/{id}/consultant', 'CustomerController@storeCustomerConsultant')->name('customers.consultant.store');
    Route::post('/customers/keyword', 'CustomerController@getCustomer')->name('customer.keyword');
    Route::post('/customers/keywordQueue', 'CustomerController@getCustomerQueue')->name('customer.keywordQueue');

    Route::post('/customers/all', 'CustomerController@getAllCustomer')->name('customer.all');
    Route::get('/customers/{id}/redeem-detail', 'CustomerController@redeemInvoice')->name('customer.redeem');
    Route::patch('/customers/{id}/void-redeem-invoice', 'CustomerController@voidInvoicePoint')->name('customer.void.redeem');


    Route::get('/{id}/editAnamnesa', 'CustomerController@editAnamnesa')->name('customer.anamnesa.editAnamnesa');
    Route::post('/customers/{id}/updateAnamnesa', 'CustomerController@updateAnamnesa')->name('customer.anamnesa.updateAnamnesa');
    Route::match(['put', 'patch'], '/customers/{id}/addAnamnesa', 'CustomerController@storeAnamnesa')->name('customer.anamnesa.storeAnamnesa');
    Route::match(['put', 'patch'], '/customer/{id}/delete-anamnesa', 'CustomerController@destroyAnamnesa')->name('customers.anamnesa.destroy');
    Route::get('/customers/{id}/chooseProduct', 'CustomerController@chooseProduct');

    Route::post('/customers/{id}/addConsignment', 'CustomerController@storeConsignment')->name('customer.consignment.storeConsignment');
    Route::get('/{id}/showPict', 'CustomerController@showPict')->name('consignment.showPict');
    Route::get('/{id}/showPictPhysical', 'CustomerController@showPictPhysical')->name('consignment.showPictPhysical');


    Route::post('/customers/{id}/addPhysical', 'CustomerController@storePhysical')->name('customer.physical.storePhysical');
    Route::post('/customer/{id}/delete-physical', 'CustomerController@destroyPhysical')->name('customer.physical.destroy');

    Route::resource('/customers', 'CustomerController');

    Route::post('/customers/saveMedicalConsign','CustomerController@saveMedicalConsign');
    Route::post('/customers/delMedicalConsign/{id}','CustomerController@delMedicalConsign');

    //customer birthday
    Route::get('/customer-birthdays', 'CustomerBirthdayController@index')->name('customerBirthdays.index');
    Route::get('/customer-birthdays/{id}/wa', 'CustomerBirthdayController@sendWhatsApp')->name('customerBirthdays.wa');
    Route::get('/customer-birthdays/data', 'CustomerBirthdayController@list')->name('customerBirthdays.data');
    Route::post('/customer-birthdays/wa', 'CustomerBirthdayController@store')->name('customerBirthdays.store');

    Route::get('/customer-inactive', 'CustomerInactiveController@index')->name('customerInactive.index');
    Route::get('/customer-inactive/{id}/wa', 'CustomerInactiveController@sendWhatsApp')->name('customerInactive.wa');
    Route::get('/customer-inactive/data', 'CustomerInactiveController@list')->name('customerInactive.data');
    Route::post('/customer-inactive/wa', 'CustomerInactiveController@store')->name('customerInactive.store');

    //active-invoice
    Route::get('/customers/{id}/detail', 'CustomerController@activeInvoice')->name('customer.active');
    Route::patch('/customers/{id}/void-active-invoice', 'CustomerController@voidActiveInvoice')->name('customer.void.active');
    Route::post('/customers/{id}/update-active', 'CustomerController@updateActiveInvoice')->name('customer.update.active');

    //treatment-balance
    Route::post('/customers/{id}/treatment-balance', 'CustomerController@treatmentBalance')->name('customer.treatment-balance');

    //usage
    Route::get('/usage-treatment/{id}/print', 'UsageController@printUsage')->name('usage-treatment.print');
    Route::patch('/usage-treatment/{id}/void', 'UsageController@voidUsage')->name('usage-treatment.void');
    Route::resource('/usage-treatment', 'UsageController');

    //user
    Route::post('/useraccess/reset', 'UserController@resetPassword')->name('useraccess.reset-password');
    Route::get('/changepassword', 'DashboardController@changePassword')->name('useraccess.change-password');
    Route::post('/updatepassword', 'DashboardController@updatePassword')->name('useraccess.update-password');
    Route::get('/useraccess/data', 'UserController@listData')->name('useraccess.data');
    Route::resource('/useraccess', 'UserController');

    //outlet
    Route::get('/outlets/data', 'OutletController@listData')->name('outlets.data');
    Route::resource('/outlets', 'OutletController');

    // ITEM MASTER

    //pointvalue
    Route::get('/pointValues/data', 'ItemMaster\PointValueController@listData')->name('pointValues.data');
    Route::resource('/pointValues', 'ItemMaster\PointValueController');

    //consultant
    Route::get('/consultants/data', 'ItemMaster\ConsultantController@listData')->name('consultants.data');
    Route::resource('/consultants', 'ItemMaster\ConsultantController');

    //therapist
    Route::get('/therapists/data', 'ItemMaster\TherapistController@listData')->name('therapists.data');
    Route::resource('/therapists', 'ItemMaster\TherapistController');

    //therapist schedule

app/Http/Controllers/ItemMaster/ActivityGroupController.php
<?php

namespace App\Http\Controllers\ItemMaster;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use DataTables;
use App\Models\ActivityGroup;
use Illuminate\Support\Facades\Gate;

class ActivityGroupController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            if (Gate::allows('admin') || Gate::allows('sales')) {
                return $next($request);
            }
            abort(403, 'You do not have enough access rights');
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return redirect(route('item-master.activities.index'));
    }

    /**
    * undocumented function summary
    *
    * Undocumented function long description
    *
    * @param Type $var Description
    * @return type
    * @throws conditon
    **/
    public function listActivityGroup()
    {
        $collection = ActivityGroup::all();
        $data = array();
        
        foreach ($collection as $activityGroups) {
            $row = [];
            $extra_field = '';
            $status_activity_group = '';

            if ($activityGroups->extra_field) {
                $extra_field = '&#10004;';
            }
            if ($activityGroups->status_activity_group) {
                $status_activity_group = '&#10004;';
            }
            
            $row[] = $activityGroups->activity_group_name;
            $row[] = $status_activity_group;
            $row[] = '
                        <a class="btn btn-success btn-sm" href="#" onclick="editFormActivityGroup(\''.$activityGroups->id_activity_group. '\')">
                            <i class="fa fa-edit"></i>
                            Edit
                        </a> 
                        <a class="btn btn-danger btn-sm" href="#" onclick="deleteDataActivityGroup(\''.$activityGroups->id_activity_group. '\')">
                            <i class="fa fa-trash"></i>
                            Delete
                        </a>
                    ';
            
            $data[] = $row;
        }


        return DataTables::of($data)->escapeColumns([])->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $save = new ActivityGroup;
        $save->activity_group_name = $request->activity_group_name;
        $save->status_activity_group = 1;
        $save->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return response()->json(ActivityGroup::findOrFail($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $update= ActivityGroup::findOrFail($id);
        if ($request->disable == true) {
            $update->status_activity_group = 0;
            $update->update();
            return response()->json(true);
        }
        

        $update->activity_group_name = $request->activity_group_name;
        if ($request->status_activity_group) {
            $update->status_activity_group = 1;
        } else {
            $update->status_activity_group = 0;
        }

        $update->update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete= ActivityGroup::findOrFail($id);
        if ($delete->activity_groups) {
            echo "error";
        } else {
            $delete->delete();
        }
    }
}

app/Http/Controllers/ItemMaster/CountryController.php
<?php

namespace App\Http\Controllers\ItemMaster;

use App\Http\Controllers\Controller;
use App\Models\Province;
use App\Models\Country;

use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Auth;

class CountryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            if (Gate::allows('admin')) {
                return $next($request);
            }

            abort(403, 'You do not have enough access rights');
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('item-master.countries.index');
    }

    public function listData()
    {
        $collection = Country::orderBy('created_at', 'desc')->get();

        $data = array();
        foreach ($collection as $country) {
            $row = [];

            $row[] = $country->country;
            
            $row[] = '
                        <a class="btn btn-success btn-sm" href="javascript:void(0)" onclick="editForm(\'' . $country->id_country . '\')">
                            <i class="fa fa-edit"></i>
                            Edit
                        </a>
                        <a class="btn btn-danger btn-sm" href="javascript:void(0)" onclick="deleteData(\'' . $country->id_country . '\')">
                            <i class="fa fa-trash"></i>
                            Delete
                        </a>
                    ';

            $data[] = $row;
        }

        return DataTables::of($data)->escapeColumns([])->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $save = new Country;
        $save->country   = $request->country;
        $save->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $model = Country::find($id);

        return response()->json($model);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $model = Country::find($id);

        $model->country  = $request->country;
        $model->update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Country::find($id);
        if ($model->province) {
            echo "error";
        } else {
            $model->delete();
        }
    }
}

resources/views/item-master/pointValues/form.blade.php
<div class="modal" id="modal-point" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
       <div class="modal-content">
            <form class="form-horizontal" data-toggle="validator" method="post">
                {{ csrf_field() }} {{ method_field('POST') }}
            
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="fa fa-times fa-lg"></i>   
                    </button>
                    <h3 class="modal-title"></h3>
                </div>
                
                <div class="modal-body" >
                    <input type="hidden" id="id" name="id">
                    <div class="form-group">
                        <label for="country" class="col-md-3 control-label">Point</label>
                        <div class="col-md-8">
                            <input type="number" class="form-control" id="point" name="point" autocomplete="off" required>
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Save </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Cancel</button>
                </div>
            </form>
        </div>
    </div>
 </div>

resources/views/item-master/pointValues/index.blade.php
@extends('base')

@section('title')
  List Point
@endsection

@section('style')
<link rel="stylesheet" href="{{ asset('plugins/DataTables/FixedColumns/css/fixedColumns.dataTables.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/DataTables/FixedColumns/css/fixedColumns.bootstrap.min.css') }}">

@endsection

@section('breadcrumb')
   @parent
   <li>Point</li>
@endsection

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add Point</a>
      </div>
      <div class="box-body">
        <table class="table table-striped table-bordered  nowrap table-point" style="width:100%">
        <thead>
          <tr>
              <th>Point Value</th>
              <th class="all" width="10%">Action</th>
          </tr>
        </thead>
        <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

@include('item-master.pointValues.form')
@endsection

@section('script')
<script type="text/javascript">
  var table, save_method;

  $('#datepicker, #datepicker2').datepicker({
    format: 'dd MM yyyy',
    autoclose: true,
    todayHighlight: true
  });

  $(function(){
    table = $('.table-point').DataTable({

        // "processing" : true,
        "serverside" : true,
        "ajax" : {
        "url" : "{{ route('pointValues.data') }}",
        "type" : "GET"
        }
    });

  $('#modal-point form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         var id = $('#id').val();
         if(save_method == "add") url = "{{ route('pointValues.store') }}";
         else url = "pointValues/"+id;

         $.ajax({
            url : url,
            type : "POST",
            data : $('#modal-point form').serialize(),
           success : function(data){
             console.log(data)
              $('#modal-point').modal('hide');
              table.ajax.reload();
           },
           error : function(e){
             console.log(e)
             alert("Can not Save the Data!");
           }
         });
         return false;
     }
   });

});

function addForm(){
   save_method = "add";
   $('#outlet').val('');
   $("#outlet").trigger("change");
   $('input[name=_method]').val('POST');
   $("#modal-point").modal({
      backdrop: 'static',
      keyboard: false,
      show: true
    });
   $('#modal-point form')[0].reset();
   $('.modal-title').text('Add Point');
}


function editForm(id){
   save_method = "edit";
   $('input[name=_method]').val('PUT');
   $('#modal-point form')[0].reset();
   $.ajax({
     url : "pointValues/"+id+"/edit",
     type : "GET",
     dataType : "JSON",
     success : function(data){
       $('#modal-point').modal('show');
       $('.modal-title').text('Edit Bank');

       $('#id').val(data.id_point_value);
       $('#point').val(data.point);


     },
     error : function(){
       alert("Can not Show the Data!");
     }
   });
}

function deleteData(id){
    swal({
        title: "Are you sure?",
        text: "Once deleted, you will not be able to recover this Point!",
        icon: "warning",
        buttons: {
            canceled:{
                text:'Cancel',
                value: 'cancel',
                className: 'swal-button btn-default'
            },
            deleted:{
                text:'Delete',
                value: 'delete',
                className: 'swal-button btn-danger'
            }
        },
        dangerMode: true,
    }).then((willDelete) => {
        switch (willDelete) {
            default:
                swal("Point is safe!");
                break;
            case 'delete':
                $.ajax({
                    url : "/pointValues/"+id,
                    type : "POST",
                    data : {'_method' : 'Delete', '_token' : $('meta[name=csrf-token]').attr('content')},
                    success : function(data){

                            swal("Point has been deleted!", {
                                icon: "success",
                            });
                        table.ajax.reload();
                    },
                    error : function(){
                        swal({
                            text: 'Can not Delete the Data!',
                            icon: 'error'
                        })
                    }
                });
                break;
        }
    });
}

</script>
<script rel="stylesheet" src="{{ asset('plugins/DataTables/FixedColumns/js/dataTables.fixedColumns.min.js') }}"></script>
<script rel="stylesheet" src="{{ asset('plugins/DataTables/FixedColumns/js/fixedColumns.bootstrap.min.js') }}"></script>
@endsection